# Generated by Django 4.1.7 on 2023-03-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='postText',
        ),
    ]
