# Generated by Django 4.1.7 on 2023-03-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_alter_post_authorarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.author'),
        ),
    ]
