# Generated by Django 4.1.7 on 2023-03-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_alter_post_authorarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='account',
        ),
    ]
