# Generated by Django 4.1.7 on 2023-03-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_rename_authoruser_author_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='account',
            new_name='authorUser',
        ),
    ]
